INPUT:
  AXIS_ALIGNED_BOX: True
  RANDOM_SCALE: None
MODEL:
  OVERALL_LOSS_MULTIPLIER: 10.0
  RPN:
    BBOX_REG_LOSS_WEIGHT: 20.0
    USE_EXP: True
    THRESHOLD2: 0.6
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_WEIGHT: 20.0
    CLS_LOSS_WEIGHT: 0.1
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  OPTIMIZER_NAME: "Adam"
  IMS_PER_BATCH: 8
  MAX_ITER: 34000
  BASE_LR: 0.005
  WARMUP_ITERS: 500
DATASETS:
  TRAIN: ("scannet_v2/train",)
  TEST: ("scannet_v2/val",)
OUTPUT_DIR: "./output/test28"
