INPUT:
  AXIS_ALIGNED_BOX: True
MODEL:
  RPN:
    BBOX_REG_LOSS_WEIGHT: 20.0
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_WEIGHT: 20.0
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  OPTIMIZER_NAME: "Adam"
  IMS_PER_BATCH: 8
  MAX_ITER: 34000
  BASE_LR: 0.005
  WARMUP_ITERS: 500
DATASETS:
  TRAIN: ("scannet_v2/train",)
  TEST: ("scannet_v2/val",)
OUTPUT_DIR: "./output/test3"
