INPUT:
  AXIS_ALIGNED_BOX: True
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  OPTIMIZER_NAME: "Adam"
  IMS_PER_BATCH: 8
  MAX_ITER: 33000
  BASE_LR: 0.005
  WARMUP_ITERS: 0
DATASETS:
  TRAIN: ("scannet_v2/train",)
  TEST: ("scannet_v2/val",)
OUTPUT_DIR: "./output/test"
